name: Packer Status Check

on:
  pull_request:
    branches:
      - main  

jobs:
  packer-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Packer
        run: |
          sudo apt-get update
          sudo apt-get install -y packer

      - name: Run packer fmt
        run: |
          packer fmt -check .  

      - name: Run packer validate
        run: |
          packer validate .
