---
name: Packer Status Check
permissions:
  id-token: write
  contents: read
on:
  pull_request:
    branches:
      - main

jobs:
  packer-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: latest
      - name: Run packer init
        run: packer init .
      - name: Run packer fmt
        run: |
          packer fmt -check .
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Run packer validate
        run: |
          packer build \
           -var "aws_region=${{ secrets.AWS_REGION }}" \
           -var "ami_name=${{ secrets.AMI_NAME }}" \
           -var "source_ami=${{ secrets.SOURCE_AMI }}" \
           -var "ssh_username=${{ secrets.SSH_USERNAME }}" \
           -var "vpc_id=${{ secrets.VPC_ID }}" \
           -var "subnet_id=${{ secrets.SUBNET_ID }}" \
           -var "ami_description=${{ secrets.AMI_DESCRIPTION }}" \
           -var "ssh_timeout=10m" \
           packer-template.pkr.hcl
