name: Packer Status Check

on:
  pull_request:
    branches:
      - main  
env:
  PRODUCT_VERSION: "1.10.0" # or: "latest"

jobs:
  packer-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Run packer fmt
        run: |
          packer fmt -check .  

      - name: Run packer init
        id: init
        run: "packer init ."

      - name: Run packer validate
        run: |
          packer validate .
