name: Packer Status Check

# Permissions needed for the workflow
permissions:
  id-token: write
  contents: read

on:
  pull_request:
    branches:
      - main
env:
  PRODUCT_VERSION: "1.10.0" # or: "latest"

jobs:
  packer-check:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Packer
      - name: Set up Packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      # Step 4: Run Packer fmt
      - name: Run packer fmt
        run: |
          packer fmt -check .
        shell: bash
        continue-on-error: false

      # Step 5: Configure AWS Credentials (if needed)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 6: Validate Packer template
      # If this command fails, the PR cannot be merged
      - name: Run packer validate
        run: |
          packer validate \
            -var "aws_region=${{ secrets.AWS_REGION }}" \
            -var "ami_name=${{ secrets.AMI_NAME }}" \
            -var "source_ami=${{ secrets.SOURCE_AMI }}" \
            -var "ssh_username=${{ secrets.SSH_USERNAME }}" \
            -var "vpc_id=${{ secrets.VPC_ID }}" \
            -var "subnet_id=${{ secrets.SUBNET_ID }}" \
            -var "ami_description=${{ secrets.AMI_DESCRIPTION }}" \
            -var "ssh_timeout=10m" \
            packer-template.pkr.hcl
