name: Packer Build Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Run packer validate
        run: |
          packer validate \
            -var "aws_region=${{ secrets.AWS_REGION }}" \
            -var "base_ami_name=${{ secrets.BASE_AMI_NAME }}" \
            -var "source_ami=${{ secrets.SOURCE_AMI }}" \
            -var "ssh_username=${{ secrets.SSH_USERNAME }}" \
            -var "vpc_id=${{ secrets.VPC_ID }}" \
            -var "subnet_id=${{ secrets.SUBNET_ID }}" \
            -var "ami_description=${{ secrets.AMI_DESCRIPTION }}" \
            -var "ssh_timeout=${{ secrets.SSH_TIMEOUT }}" \
            -var "instance_type=${{ secrets.INSTANCE_TYPE }}" \
            -var "project_path=/home/runner/work/webapp/webapp.zip" \
            -var "DB_HOST=${{ secrets.POSTGRES_HOST }}" \
            -var "DB_USER=${{ secrets.POSTGRES_USERNAME }}" \
            -var "DB_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" \
            -var "DB_NAME=${{ secrets.POSTGRES_DATA